info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
---
grails:
  profile: web
  codegen:
    defaultPackage: datasources
---
dataSource:
  pooled: true
  driverClassName: org.h2.Driver
  dbCreate: create-drop
  url: jdbc:h2:mem:books;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

